name: On Push Master CI

on:
 push:
  branches:
   - master
   
jobs:
 test:
  name: Run Unit Test
  runs-on: [ubuntu-latest]
  steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
       restore-keys: |
        ${{ runner.os }}-gradle-
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
 
 build:
  name: Generate Apk
  runs-on: [ubuntu-latest]
  steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
       restore-keys: |
        ${{ runner.os }}-gradle-
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
        
#  build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
#     - uses: actions/cache@v1
#       with:
#        path: ~/.m2/repository
#        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
#        restore-keys: |
#         ${{ runner.os }}-gradle-
#     - name: Make Gradle executable
#       run: chmod +x ./gradlew
#     - name: Build debug APK
#       run: bash ./gradlew assembleDebug --stacktrace
#     - name: Upload APK
#       uses: actions/upload-artifact@v1
#       with:
#         name: app
#         path: app/build/outputs/apk/debug/app-debug.apk
#     - name: Releasing using Hub
#       uses: ShaunLWM/action-release-debugapk@master
#       env:
#        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
#        APP_FOLDER: app
#        RELEASE_TITLE: New Debug Build
